### ISSUE TITLE
Why --comp xz?

### ISSUE THREAD

**Issue by probonopd** [lvml/makeaoi#4]
Why is `--comp xz` recommended?

**Comment by lvml** [comment]
I expect "application overlay images" that "bundle every dependency" to be of significant size, and using xz for compressing them sounds like good advice.
Or do you see a reason against this recommendation?

**Comment by probonopd** [comment]
Yes, slower startup time with only marginally smaller AppImages. The default compression (with no `--comp ...`) is recommended.

**Comment by lvml** [comment]
What compression method is used by default?

**Comment by probonopd** [comment]
squashfs gzip compression

**Comment by lvml** [comment]
Ok, I removed the "xz" recommendation - people who like the smaller file size will hopefully find out themselves ;-)
